daung/inventory/urls.py
from django.urls import path

from . import views

app_name = "inventory"

urlpatterns = [
    path("", views.index, name="index"),
    path("items/", views.items, name="items"),
    path("items/b/<int:bin_id>", views.items, name="bin_items"),
    path("add_bin/", views.add_bin, name="add_bin"),
    path("add_item/", views.add_item, name="add_item"),
    path("add_item/<int:bin_id>", views.add_item, name="add_bin_item"),
    path("edit_bin/", views.edit_bin, name="edit_bin"),
    path("edit_item/", views.edit_item, name="edit_item"),
    path("edit_item/<int:bin_id>", views.edit_item, name="edit_bin_item"),
    path("item_logs/<int:page>", views.item_logs, name="item_logs"),
]

daung/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("daung.inventory.urls")),
    path('users/', include('daung.users.urls')),
]

daung/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name="index"),
    path('create', views.create_page, name="create"),
    path('login', views.login_page, name="login"),
    path('logout', views.logout_page, name="logout"),
]

daung/inventory/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bin(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.name}"
    

class Item(models.Model):
    name = models.CharField(max_length=128)
    quantity = models.PositiveIntegerField()
    image = models.ImageField(upload_to='items/', blank=True, null=True)
    bin = models.ForeignKey(Bin, on_delete=models.SET_NULL, related_name='items', blank=True, null=True)

    def __str__(self):
        return f"{self.name} | {self.quantity}"
    

class Log(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    username = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, blank=True, null=True)
    ondelete_last_item = models.CharField(max_length=255, blank=True, null=True)
    bin = models.ForeignKey(Bin, on_delete=models.SET_NULL, blank=True, null=True)
    ondelete_last_bin = models.CharField(max_length=255, blank=True, null=True)
    quantity = models.PositiveIntegerField(blank=True, null=True)
    previous_quantity = models.PositiveIntegerField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.timestamp} - {self.username} - {self.item.name}"

daung/users/models.py
from django.db import models

# Create your models here.

daung/inventory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse

from itertools import zip_longest

from .models import Bin, Item, Log

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    bins = Bin.objects.all()
    return render(request, "inventory/index.html", {'bins': bins})


# Create your views here.
def items(request, bin_id=None):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    if bin_id:
        bin_instance = get_object_or_404(Bin, id=bin_id)
        bins = Bin.objects.all()
        items = Item.objects.filter(bin=bin_instance)
        
        context = {
            'items': items,
            'selected_bin': bin_instance,
            'bins': bins,
        }
    else:
        bins = Bin.objects.all()
        items = Item.objects.all()
        
        context = {
            'items': items,
            'bins': bins,
        }

    return render(request, "inventory/items.html", context)


# Create your views here.
def add_bin(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    if request.method == "POST":
        name = request.POST.get('name')

        if name:
            Bin.objects.create(name=name)
            return redirect('inventory:edit_bin')
        
    return render(request, "inventory/add_bin.html")


# Create your views here.
def add_item(request, bin_id=None):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    bins = Bin.objects.all()

    if request.method == "POST":
        name = request.POST.get('name')
        quantity = request.POST.get('quantity')
        bin_id = request.POST.get('bin')

        image = request.FILES.get('image')

        if name and quantity:
            bin_instance = Bin.objects.get(id=bin_id) if bin_id else None
            Item.objects.create(
                name=name,
                quantity=quantity,
                image=image,
                bin=bin_instance,
            )
            return redirect('inventory:items')
    
    if bin_id:
        bin_instance = get_object_or_404(Bin, id=bin_id)
        context = {
            'bins': bins,
            'selected_bin': bin_instance
        }
    else:
        context = {'bins': bins}

    return render(request, "inventory/add_item.html", context)


def edit_bin(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    if request.method == "POST":
        bin_ids = request.POST.getlist('bin_ids')
        bin_names = request.POST.getlist('bin_names')
        original_bin_names = request.POST.getlist('original_bin_names')
        removed_bins = request.POST.getlist('removed_bins')
        
        errors = []
        
        # Iterate through each bin and update it
        for bin_id, bin_name, original_bin_name, removed_bin in zip_longest(
            bin_ids, bin_names, original_bin_names, removed_bins, fillvalue=None):
            try: 
                bin = Bin.objects.get(id=bin_id)
                if removed_bin == '1':
                    bin.delete()
                else:
                    bin.name = bin_name
                    bin.save()
            except Bin.DoesNotExist:
                # Handle the case where the bin has been deleted
                errors.append(f"You cannot change {original_bin_name} because it has been deleted by another user.")

        # Notify the user of the errors if there are any
        if errors:
            for error in errors:
                messages.error(request, error)

        # Redirect back to the index page
        return redirect('inventory:index')
    
    bins = Bin.objects.all()
    return render(request, "inventory/edit_bin.html", {'bins': bins})


def edit_item(request, bin_id=None):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    if request.method == "POST":
        item_ids = request.POST.getlist('item_ids')
        item_names = request.POST.getlist('item_names')
        original_item_names = request.POST.getlist('original_item_names')
        item_qtys = request.POST.getlist('item_qtys')
        original_item_qtys = request.POST.getlist('original_item_qtys')
        item_imgs = request.FILES.getlist('item_imgs')
        removed_items = request.POST.getlist('removed_items')

        errors = []
        
        # Iterate through each item and update it
        for item_id, item_name, original_item_name, item_qty, original_item_qty, item_img, removed_item in zip_longest(
            item_ids, item_names, original_item_names, item_qtys, original_item_qtys, item_imgs, removed_items, fillvalue=None):
            try: 
                item = Item.objects.get(id=item_id)

                if removed_item == '1':
                    item.delete()
                else:
                    if item.bin:
                        bin = item.bin 
                        bin_name = item.bin.name
                    else:
                        bin = None
                        bin_name = None

                    if item_qty != original_item_qty:
                        Log.objects.create(
                            username=request.user,
                            item=item,
                            ondelete_last_item = item.name,
                            bin = bin,
                            ondelete_last_bin = bin_name,
                            quantity = item_qty,
                            previous_quantity = original_item_qty
                        )

                    item.image = item_img
                    item.name = item_name
                    item.quantity = item_qty
                    item.save()
            except Item.DoesNotExist:
                # Handle the case where the item has been deleted
                errors.append(f"You cannot change {original_item_name} because it has been deleted by another user.")

        # Notify the user of the errors if there are any
        if errors:
            for error in errors:
                messages.error(request, error)

        # Redirect back to the index page
        return redirect('inventory:items')
    
    if bin_id:
        bin_instance = get_object_or_404(Bin, id=bin_id)
        bins = Bin.objects.all()
        items = Item.objects.filter(bin=bin_instance)
        
        context = {
            'items': items,
            'selected_bin': bin_instance,
            'bins': bins,
        }
    else:
        bins = Bin.objects.all()
        items = Item.objects.all()
        
        context = {
            'items': items,
            'bins': bins,
        }
    
    return render(request, "inventory/edit_item.html", context)


def item_logs(request, page=0):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    
    logs = Log.objects.order_by('-id')[20*page:20*(page+1)]
    bins = Bin.objects.all()

    context = {
        'logs': logs,
        'bins': bins,
        'next_page': page+1,
    }
    
    return render(request, "inventory/item_log.html", context)

daung/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse


# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return HttpResponseRedirect(reverse("management:index"))


def create_page(request):
    if request.method == "POST":
        first_name = request.POST.get("firstname")
        last_name = request.POST.get("lastname")
        email = request.POST.get("email")
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            user = User.objects.create_user(username=username, 
                                            first_name=first_name, 
                                            last_name=last_name, 
                                            email=email, 
                                            password=password)
        else:
            return redirect("users:create")
        
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("inventory:index"))
        else:
            return render(request, "users/create.html", {
                "form_data": {
                    'first_name': first_name,
                    'last_name': last_name,
                    'email': email,
                    'username': username,                    
                },
                "message": "Invalid user information. Try again"
            })

    return render(request, "users/create.html")


# Create your views here.
def login_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            user = authenticate(request,
                                username=username,
                                password=password)
        else:
            return redirect("users:login")
            
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("inventory:index"))
        else:
            return render(request, "users/login.html", {
                "form_data": {
                    'username': username,
                },
                "message": "Invalid credentials"
            })

    return render(request, "users/login.html")


def logout_page(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out"
    })

daung/templates/inventory/add_bin.html
{% extends "base.html" %}

{% block title %}
    Add new bin
{% endblock %}

{% block header %}
    Add new bin
{% endblock %}

{% block body %}
<form action="{% url 'inventory:add_bin' %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Name" required>
    <input type="submit" value="Add Bin">
</form>
{% endblock %}

daung/templates/inventory/add_item.html
{% extends "base.html" %}

{% block title %}
    Add new item
{% endblock %}

{% block header %}
    Add new item
{% endblock %}

{% block body %}
    <form action="{% url 'inventory:add_item' %}" method="post">
        {% csrf_token %}
        <input type="file" name="image" accept="image/*" placeholder="Image">
        <input type="text" name="name" placeholder="Name" required>
        <input type="number" name="quantity" placeholder="Quantity" min="1" required>
        <select id="bin" name="bin" {% if not bins %} disabled {% endif %}>
            {% if bins %}
                <option value="" {% if not selected_bin %} selected {% endif %} disabled>Select a bin</option>
                {% for bin in bins %}
                    <option value="{{ bin.id }}" {% if selected_bin.id == bin.id %} selected {% endif %}>{{ bin.name }}</option>
                {% endfor %}
            {% else %}
                <option value="" selected disabled>No bins available</option>
            {% endif %}
        </select>
        <input type="submit" value="Add Item">
    </form>
{% endblock %}

daung/templates/inventory/edit_bin.html
{% extends "base.html" %}
{% load custom_tags static %}

{% block title %}
    Edit Bins
{% endblock %}

{% block body %}

    {% get_nav "Edit Bins" %}

    <div class="menu">
        <a href="{% url 'inventory:index' %}">Bins</a>
        <a href="{% url 'inventory:items' %}">Items</a>
    
        <input type="text" id="search-bar" class="form-control" placeholder="Search">
    </div>

    {% if bins %}

    <form action="{% url 'inventory:edit_bin' %}" method="post">
        {% csrf_token %}
        <ul class="bins" id="bins-list">
            
        {% for bin in bins %}
            <li id="{{ bin.id }}" class="bin qdata">
                <input type="hidden" name="bin_ids" value="{{ bin.id }}">
                <input type="hidden" name="original_bin_names" value="{{ bin.name }}">

                <input type="text" name="bin_names" placeholder="Name" value="{{ bin.name }}" required>
                <span class="qtext d-none">{{ bin.name }}</span>

                <button type="button" onclick="removeBin('{{ bin.id }}')" class="remove-button">Remove bin</button>
                <button type="button" onclick="cancelRemoveBin('{{ bin.id }}')" class="cancel-button d-none">Cancel</button>
                <input type="hidden" name="removed_bins" value="" class="removed-bins">
            </li>
        {% endfor %}
            
        </ul>

        <div class="button-container">
            <a href="{% url 'inventory:add_bin' %}">Add bin</a>
        </div>

        <div class="button-container">
            <a href="{% url 'inventory:index' %}">Cancel</a>
            <input type="submit" value="Submit changes">
        </div>
    </form>

    {% else %}

        <div>No Bins. Go back.</div>
        <div class="button-container">
            <a href="{% url 'inventory:index' %}">Go back</a>
        </div>
        
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/loadquery.js' %}"></script>
    <script>
        function removeBin(binId) {
            const binElement = document.getElementById(binId);
            const removedBinsInput = binElement.querySelector('.removed-bins');
            removedBinsInput.value = '1';
            binElement.classList.add('removed');
            binElement.querySelector('.remove-button').classList.add('d-none');
            binElement.querySelector('.cancel-button').classList.remove('d-none');
        }

        function cancelRemoveBin(binId) {
            const binElement = document.getElementById(binId);
            const removedBinsInput = binElement.querySelector('.removed-bins');
            removedBinsInput.value = '';
            binElement.classList.remove('removed');
            binElement.querySelector('.remove-button').classList.remove('d-none');
            binElement.querySelector('.cancel-button').classList.add('d-none');
        }
    </script>
{% endblock %}

daung/templates/inventory/edit_item.html
{% extends "base.html" %}
{% load custom_tags static %}

{% block title %}
    Edit Items
{% endblock %}

{% block body %}

    {% get_nav "Edit Items" %}

    <div class="menu">
        <a href="{% url 'inventory:index' %}">Bins</a>
        <a href="{% url 'inventory:items' %}">Items</a>
    
        <input type="text" id="search-bar" class="form-control" placeholder="Search">
    </div>

    {% if items %}

    <form action="{% url 'inventory:edit_item' %}" method="post">
        {% csrf_token %}
        <ul class="items">

        {% for item in items %}
            <li id="{{ item.id }}" class="item qdata">
                <!-- Item ID -->
                <input type="hidden" name="item_ids" value="{{ item.id }}">

                <!-- Item image -->
                <input type="file" name="item_imgs" accept="image/*" placeholder="Image">

                <!-- Item name -->
                <input type="hidden" name="original_item_names" value="{{ item.name }}">
                <input type="text" name="item_names" placeholder="Name" value="{{ item.name }}" required>
                <span class="qtext d-none">{{ item.name }}</span>

                <!-- Item quantity -->
                <input type="hidden" name="original_item_qtys" value="{{ item.quantity }}">
                <input type="number" name="item_qtys" placeholder="Quantity" min="0" value="{{ item.quantity }}" required>

                <!-- Remove item -->
                <button type="button" onclick="removeItem('{{ item.id }}')" class="remove-button">Remove item</button>
                <button type="button" onclick="cancelRemoveItem('{{ item.id }}')" class="cancel-button d-none">Cancel</button>
                <input type="hidden" name="removed_items" value="" class="removed-items">
            </li>
        {% endfor %}

        </ul>

        <div class="button-container">
            <a href="{% url 'inventory:add_item' %}">Add item</a>
        </div>

        <div class="button-container">
            <a href="{% url 'inventory:items' %}">Cancel</a>
            <input type="submit" value="Submit changes">
        </div>


    {% else %}

        <div class="button-container">
            {% if selected_item %}
                <a href="{% url 'inventory:add_item_item' selected_item.id %}">Edit items</a>
            {% else %}
                <a href="{% url 'inventory:add_item' %}">Edit items</a>
            {% endif %}
        </div>

    {% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/loadquery.js' %}"></script>
    <script>
        function removeItem(itemId) {
            const itemElement = document.getElementById(itemId);
            const removedItemsInput = itemElement.querySelector('.removed-items');
            removedItemsInput.value = '1';
            itemElement.classList.add('removed');
            itemElement.querySelector('.remove-button').classList.add('d-none');
            itemElement.querySelector('.cancel-button').classList.remove('d-none');
        }

        function cancelRemoveItem(itemId) {
            const itemElement = document.getElementById(itemId);
            const removedItemsInput = itemElement.querySelector('.removed-items');
            removedItemsInput.value = '';
            itemElement.classList.remove('removed');
            itemElement.querySelector('.remove-button').classList.remove('d-none');
            itemElement.querySelector('.cancel-button').classList.add('d-none');
        }
    </script>
{% endblock %}

daung/templates/inventory/index.html
{% extends "base.html" %}
{% load custom_tags static %}

{% block title %}
    Bins
{% endblock %}

{% block body %}

    {% get_nav "Bins" %}

    <div class="menu">
        <a href="{% url 'inventory:index' %}">Bins</a>
        <a href="{% url 'inventory:items' %}">Items</a>
        <a href="{% url 'inventory:item_logs' 0 %}">Changes History</a>

        <input type="text" id="search-bar" class="form-control" placeholder="Search">
    </div>

    {% if bins %}

        <ul class="bins">

        {% for bin in bins %}
            <li id="{{ bin.id }}" class="bin qdata">
                <a href="{% url 'inventory:bin_items' bin.id %}">
                    <span class="qtext">{{ bin.name }}</span>
                </a>
            </li>
        {% endfor %}

        </ul>

        <div class="button-container">
            <a href="{% url 'inventory:edit_bin' %}">Edit bins</a>
        </div>

    {% else %}

        <div class="button-container">
            <a href="{% url 'inventory:add_bin' %}">Add bin</a>
        </div>
        
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/loadquery.js' %}"></script>
{% endblock %}

daung/templates/inventory/item_log.html
{% extends "base.html" %}
{% load custom_tags static %}

{% block title %}
    Change History
{% endblock %}

{% block body %}

    {% get_nav "Bins" %}

    <div class="menu">
        <a href="{% url 'inventory:index' %}">Home</a>
    
        <input type="text" id="search-bar" class="form-control" placeholder="Search">
    </div>

    {% if logs %}

        <ul class="logs">

        {% for log in logs %}
            <li id="{{ log.id }}" class="log qdata">
                <div>
                    <span class="qtext">{{ log.timestamp }}</span>
                    <span class="qtext">{{ log.username }}</span>
                    <span class="qtext">
                        {% if log.item %} 
                            {{ log.item.name }}
                        {% else %}
                            {{ log.ondelete_last_item }}
                        {% endif %}
                    </span>
                    <span class="qtext">
                        {% if log.bin %}
                            {{ log.bin }}
                        {% else %}
                            {% if log.ondelete_last_bin %}
                                {{ log.ondelete_last_bin }}
                            {% else %}
                                None
                            {% endif %}
                        {% endif %}
                    </span>
                    <span class="">{{ log.quantity }}</span>
                    <span class="">{{ log.previous_quantity }}</span>
                </div>
            </li>
        {% endfor %}

        </ul>

        <div class="button-container">
            <a href="{% url 'inventory:item_logs' next_page %}">Edit bins</a>
        </div>

    {% else %}

        <span>No changes made yet</span>
        
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/loadquery.js' %}"></script>
{% endblock %}

daung/templates/inventory/items.html
{% extends "base.html" %}
{% load custom_tags static %}

{% block title %}
    {% if not selected_bin %}
        Items
    {% else %}
        Items - {{ bin.name }}
    {% endif %}
{% endblock %}

{% block header %}
    Items
{% endblock %}

{% block body %}

    {% get_nav "Items" %}

    <div class="menu">
        <a href="{% url 'inventory:index' %}">Bins</a>
        <a href="{% url 'inventory:items' %}">Items</a>
        <a href="{% url 'inventory:item_logs' 0 %}">Changes History</a>
    
        <select id="bin" name="bin" onchange="redirectToBin()">
            <option value="-1" {% if not selected_bin %} selected {% endif %}>All items</option>
            {% for bin in bins %}
                <option value="{{ bin.id }}" {% if selected_bin.id == bin.id %} selected {% endif %}>{{ bin.name }}</option>
            {% endfor %}
        </select>
    
        <input type="text" id="search-bar" class="form-control" placeholder="Search">
    </div>

    {% if items %}

        <ul class="items">

        {% for item in items %}
            <li class="item qdata">
                <div>
                    <span class="qtext">{{ item.name }}</span> x {{ item.quantity }}
                </div>
            </li>
        {% endfor %}

        </ul>

        <div class="button-container">
            {% if selected_bin %}
                <a href="{% url 'inventory:edit_bin_item' selected_bin.id %}">Edit items</a>
            {% else %}
                <a href="{% url 'inventory:edit_item' %}">Edit items</a>
            {% endif %}
        </div>

    {% else %}

        <div class="button-container">
            {% if selected_bin %}
                <a href="{% url 'inventory:add_bin_item' selected_bin.id %}">Add items</a>
            {% else %}
                <a href="{% url 'inventory:add_item' %}">Add items</a>
            {% endif %}
        </div>

    {% endif %}

{% endblock %}

{% block extra_js %}
    <script>
        function redirectToBin() {
            const binId = document.getElementById('bin').value;
            let url = '';

            if (binId === '-1') {
                url = "{% url 'inventory:items' %}";
            } else {
                url = `/items/b/${binId}`
            }

            window.location.href = url;
        }
    </script>

    <script type="text/javascript" src="{% static 'js/loadquery.js' %}"></script>
{% endblock %}